### ISSUE TITLE
Goodreads API failure and some workaround findings

### ISSUE THREAD

**Issue by jregan** [AFNetworking/AFOAuth1Client#20]
I'm having troubles using AFOAuth1Client, specifically the access_token piece. Goodreads is Oauth 1, not 1a if that makes a difference.

They suggest using the OAuthConsumer code which does work - I was able to look at that to determine what some of the differences were between requests generated between the two libraries.

I only have a hacked and working version of this but not a clean code implementation. (It certainly doesn't take into account how compatible this might be with other OAuth1 access_token requests either.) 

But this what I've found so far - I'll comment on this further as I find out more.

1) Their access_token request is a GET not a POST
2) The access_token request construction code should only have the oauth_token query param. 

``` objective-c
 - (void)acquireOAuthAccessTokenWithPath...
{
    // GOODREADS HACK CHANGE
    //NSMutableDictionary *parameters = [[self OAuthParameters] mutableCopy];
    NSMutableDictionary *parameters = [[NSMutableDictionary alloc] init];
```

3) Then I add the [OAuthParameters] to the mutableParams dict once we're creating the URLRequest

``` objective-c
// GOODREADS HACK CHANGE
// new method adapted from AFOAuth1Client.requestWithMethod
- (NSMutableURLRequest *)requestForAccessTokenWithMethod:(NSString *)method
                                          path:(NSString *)path
                                    parameters:(NSDictionary *)parameters
                                    requestToken:(AFOAuth1Token *) requestToken
{
    NSMutableDictionary *mutableParameters = parameters ? [parameters mutableCopy] :          [NSMutableDictionary dictionary];
    // GOODREADS HACK CHANGE
    [mutableParameters addEntriesFromDictionary:[self OAuthParameters]];
```

4) The OAuth signature creation code has 2 differences:
1. The request token secret is used in conjunction with the application secret. 
2. The query param in this case oauth_token is included with the authorization params. In this instance, the request string used in the OAuth sig contains "oauth_token" twice -

GET&http%3A%2F%2Fwww.goodreads.com%2Foauth%2Faccess_token&oauth_consumer_key%3D[consumerKeyValue]%26oauth_nonce%3D9383CF2A-D611-4C93-9B6E-F3B0D6E77A3E%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1359649280%26oauth_token%3DEzn4noEYUA3aCWrQL99Q%26oauth_token%3DEzn4noEYUA3aCWrQL99Q%26oauth_version%3D1.0

I did create an alternate signature method that does this - I can post my hacked version of AFOAuth1Client if you'd like...but I can't say it's pretty ;)

**Comment by mattt** [comment]
Can you try again with the latest version in master? I just merged several pull requests that may fix this issue.

**Comment by jregan** [comment]
Sorry it took me so long to get back.

No, that didn't solve the problem. The same issues as I've listed above.

Here's some code I hacked together for item 4 up there -

> 4) The OAuth signature creation code has 2 differences:
> 1. The request token secret is used in conjunction with the application secret. 
> 2. The query param in this case oauth_token is included with the authorization params. In this instance, the request string used in the OAuth sig contains "oauth_token" twice -

...it's an alternate version of the OAuth signature method in AFOAuth1Client OAuthSignatureForMethod that I'm using for the access_token call.

``` objective-c
- (NSString *)alternateOAuthSignatureForMethod:(NSString *)method
                                          path:(NSString *)path
                                    parameters:(NSDictionary *)parameters
                                  requestToken:(AFOAuth1Token*) requestToken
{
    NSMutableURLRequest *request = [super requestWithMethod:@"GET" path:path parameters:parameters];
    [request setHTTPMethod:method];

    //NSString *tokenSecret = requestToken ? requestToken.secret : nil;
    NSString *tokenSecret = requestToken ? requestToken.secret : @"";

    // FIXME : code from AFHMACSHA1Signature
    //NSString *secret = tokenSecret ? tokenSecret : @"";
    NSString *secretString = [NSString stringWithFormat:@"%@&%@", self.secret, tokenSecret];
    NSData *secretStringData = [secretString dataUsingEncoding:self.stringEncoding];

    // FIXME : ADDED CODE - Goodreads hack
    // manually adding the oauth token to the query components
    NSArray *queryComponents = [[[request URL] query] componentsSeparatedByString:@"&"];
    NSMutableArray *mutableQueryComponents = [[NSMutableArray alloc] init];
    [mutableQueryComponents addObjectsFromArray:queryComponents];
    [mutableQueryComponents addObject:[NSString stringWithFormat:@"oauth_token=%@", requestToken.key]];

    // FIXME : ADDED CODE - Goodreads hack (using query components array created above instead of [request URL] query])
    //    NSString *queryString = AFPercentEscapedQueryStringPairMemberFromStringWithEncoding([[[[[request URL] query] componentsSeparatedByString:@"&"] sortedArrayUsingSelector:@selector(caseInsensitiveCompare:)] componentsJoinedByString:@"&"], self.stringEncoding);
    NSString *queryString = AFPercentEscapedQueryStringPairMemberFromStringWithEncoding([[mutableQueryComponents sortedArrayUsingSelector:@selector(caseInsensitiveCompare:)] componentsJoinedByString:@"&"], self.stringEncoding);

    NSString *requestString = [NSString stringWithFormat:@"%@&%@&%@", [request HTTPMethod], AFPercentEscapedQueryStringPairMemberFromStringWithEncoding([[[request URL] absoluteString] componentsSeparatedByString:@"?"][0], self.stringEncoding), queryString];
    NSData *requestStringData = [requestString dataUsingEncoding:self.stringEncoding];

    // FIXME
    //NSLog(@"Alternate AF query string - %@", queryString);
    NSLog(@"Alternate AF request string - %@", requestString);

    uint8_t digest[CC_SHA1_DIGEST_LENGTH];
    CCHmacContext cx;
    CCHmacInit(&cx, kCCHmacAlgSHA1, [secretStringData bytes], [secretStringData length]);
    CCHmacUpdate(&cx, [requestStringData bytes], [requestStringData length]);
    CCHmacFinal(&cx, digest);

    return AFEncodeBase64WithData([NSData dataWithBytes:digest length:CC_SHA1_DIGEST_LENGTH]);

}
```

**Comment by mattt** [comment]
This should have been fixed with the latest 0.2 release, or the latest in master, at least. Thanks for posting your workaround, @jregan.
